# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:/Users/Public/QSWATPlus3/QSWATPlus\ui_Drawshape.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os.path
from qgis.PyQt.QtGui import QIcon

class Ui_drawshapedialog(object):

    def setupUi(self, drawshapedialog):
        drawshapedialog.setObjectName("drawshapedialog")
        drawshapedialog.resize(430, 450)
        self.button_box = QtWidgets.QDialogButtonBox(drawshapedialog)
        self.button_box.setGeometry(QtCore.QRect(50, 410, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.groupBox_selectcategory = QtWidgets.QGroupBox(drawshapedialog)
        self.groupBox_selectcategory.setGeometry(QtCore.QRect(20, 10, 391, 61))
        self.groupBox_selectcategory.setObjectName("groupBox_selectcategory")
        self.comboBox_selectcategory = QtWidgets.QComboBox(self.groupBox_selectcategory)
        self.comboBox_selectcategory.setGeometry(QtCore.QRect(250, 30, 121, 20))
        self.comboBox_selectcategory.setObjectName("comboBox_selectcategory")
        self.comboBox_selectcategory.addItem("")
        self.comboBox_selectcategory.addItem("")
        self.comboBox_selectcategory.addItem("")
        self.comboBox_selectcategory.addItem("")
        self.Labletest = QtWidgets.QLabel(self.groupBox_selectcategory)
        self.Labletest.setGeometry(QtCore.QRect(150, 30, 130, 21))
        self.Labletest.setObjectName("Labletest")
        self.dPolygonButton = QtWidgets.QPushButton(self.groupBox_selectcategory)
        self.dPolygonButton.setGeometry(QtCore.QRect(110, 30, 31, 23))
        self.dPolygonButton.setObjectName("dPolygonButton")
        self.dRectangleButton = QtWidgets.QPushButton(self.groupBox_selectcategory)
        self.dRectangleButton.setGeometry(QtCore.QRect(30, 30, 31, 23))
        self.dRectangleButton.setObjectName("dRectangleButton")
        self.dCircleButton = QtWidgets.QPushButton(self.groupBox_selectcategory)
        self.dCircleButton.setGeometry(QtCore.QRect(70, 30, 31, 23))
        self.dCircleButton.setObjectName("dCircleButton")
        self.groupBox_status = QtWidgets.QGroupBox(drawshapedialog)
        self.groupBox_status.setGeometry(QtCore.QRect(20, 80, 391, 320))
        self.groupBox_status.setObjectName("groupBox_status")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_status)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 351, 250))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setColumnWidth(0, 80)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.setColumnWidth(1, 10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.setColumnWidth(2, 100)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.setColumnWidth(3, 15)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.setColumnWidth(4, 15)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.setColumnWidth(5, 15)

        self.toolButton_Merge = QtWidgets.QPushButton(self.groupBox_status)
        self.toolButton_Merge.setGeometry(QtCore.QRect(40, 290, 90, 21))
        self.toolButton_Merge.setObjectName("toolButton_Merge")
        self.toolButton_load = QtWidgets.QToolButton(self.groupBox_status)
        self.toolButton_load.setGeometry(QtCore.QRect(145, 290, 90, 21))
        self.toolButton_load.setObjectName("toolButton_load")
        self.toolButton_Refresh = QtWidgets.QToolButton(self.groupBox_status)
        self.toolButton_Refresh.setGeometry(QtCore.QRect(250, 290, 90, 21))
        self.toolButton_Refresh.setObjectName("toolButton_Refresh")

        self.retranslateUi(drawshapedialog)
        self.button_box.accepted.connect(drawshapedialog.accept)
        self.button_box.rejected.connect(drawshapedialog.reject)
        QtCore.QMetaObject.connectSlotsByName(drawshapedialog)

    def retranslateUi(self, drawshapedialog):
        _translate = QtCore.QCoreApplication.translate
        icon_folder = 'resources'
        drawshapedialog.setWindowTitle(_translate("drawshapedialog", "Draw Shape"))
        self.groupBox_selectcategory.setTitle(_translate("drawshapedialog", "Select Category of shapefile and Draw "))
        self.comboBox_selectcategory.setItemText(0, _translate("drawshapedialog", "Reservoir"))
        self.comboBox_selectcategory.setItemText(1, _translate("drawshapedialog", "Ponds"))
        self.comboBox_selectcategory.setItemText(2, _translate("drawshapedialog", "Wetland"))
        self.comboBox_selectcategory.setItemText(3, _translate("drawshapedialog", "Playas"))
        self.Labletest.setText(_translate("drawshapedialog", "Reservoir"))

        self.dPolygonButton.setText(_translate("drawshapedialog", ""))
        icon_filename_polygon = 'icon_DrawP.png'
        icon_path_polygon = os.path.join(os.path.dirname(__file__), icon_folder, icon_filename_polygon)
        icon_polygon = QIcon(icon_path_polygon)
        self.dPolygonButton.setIcon(icon_polygon)
        self.dPolygonButton.setToolTip('Draw Polygon')

        self.dRectangleButton.setText(_translate("drawshapedialog", ""))
        icon_filename_rectangle = 'icon_DrawR.png'
        icon_path_rectangle = os.path.join(os.path.dirname(__file__), icon_folder, icon_filename_rectangle)
        icon_rectangle = QIcon(icon_path_rectangle)
        self.dRectangleButton.setIcon(icon_rectangle)
        self.dRectangleButton.setToolTip('Draw Rectangle')

        self.dCircleButton.setText(_translate("drawshapedialog", ""))
        icon_filename_circle = 'icon_DrawC.png'
        icon_path_circle = os.path.join(os.path.dirname(__file__), icon_folder, icon_filename_circle)
        icon_circle = QIcon(icon_path_circle)
        self.dCircleButton.setIcon(icon_circle)
        self.dCircleButton.setToolTip('Draw Circle')

        self.groupBox_status.setTitle(_translate("drawshapedialog", "Status / Edit polygons"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("drawshapedialog", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("drawshapedialog", "RES"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("drawshapedialog", "Area"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("drawshapedialog", "DEL"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("drawshapedialog", "EDT"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("drawshapedialog", "MOV"))
        self.toolButton_Merge.setText(_translate("drawshapedialog", "Merge"))
        self.toolButton_load.setText(_translate("drawshapedialog", "Load Shape"))
        self.toolButton_Refresh.setText(_translate("drawshapedialog", "Refresh"))
